core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from .views import home,projectname1,projectname2,projectform1

app_name = 'home'

urlpatterns = [
    path('',home,name='home1'),
    path('projectname1',projectname1,name='projectname1'),
    path('projectname2',projectname2,name='projectname2'),
    path('project1form',projectform1,name='projectform1')
]

home/models.py
from django.db import models

class ReleaseProject1(models.Model):
    date = models.DateField()
    release_artifact = models.CharField(max_length=100)
    release_number = models.CharField(max_length=50)
    release_path = models.CharField(max_length=100)
    service_name = models.CharField(max_length=50)
    version = models.CharField(max_length=50)
    microui = models.BooleanField()
    sql = models.BooleanField()
    uat = models.BooleanField()
    prod = models.BooleanField()
    

    def __str__(self):
        return f"{self.service_name} {self.version} ({self.release_number})"

home/views.py
from django.shortcuts import render,redirect
from django.shortcuts import render
from .models import ReleaseProject1

def home(request):
    return render(request,'home/index.html')

def projectname1(request):
    releases = ReleaseProject1.objects.all()
    print(releases)
    context= {
        'releases':releases
    }
    return render(request,'home/projectname1.html',context)

def projectname2(request):
    return render(request,'home/projectname2.html')

def projectform1(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        release_artifact = request.POST.get('release_artifact')
        release_number = request.POST.get('release_number')
        release_path = request.POST.get('release_path')
        service_name = request.POST.get('service_name')
        version = request.POST.get('version')
        microui = bool(request.POST.get('microui'))
        sql = bool(request.POST.get('sql'))
        uat = bool(request.POST.get('uat'))
        prod = bool(request.POST.get('prod'))
        print(date) 
        print(microui)
        print(prod)
        projectform1 = ReleaseProject1(date=date,release_artifact=release_artifact,release_number=release_number,release_path=release_path,service_name=service_name,version=version,microui=microui,sql=sql,uat=uat,prod=prod)
        projectform1.save()
        return redirect('home:projectname1')
    return render(request,'home/project1form.html')

home/templates/home/index.html
{% extends "base/base.html" %}
{% block content %}
{% endblock content %}

home/templates/home/project1form.html
{% extends "base/base.html" %}
{% block content %}
<div class="container">
<form method="POST" action="{% url 'home:projectform1' %}" >
    {% csrf_token %}
    <div class="form-group">
      <label for="id_date">Date</label>
      <input type="date" class="form-control" id="id_date" name="date" value="{{ object.date|default:'' }}">
    </div>
    <div class="form-group">
      <label for="id_release_artifact">Release Artifact</label>
      <input type="text" class="form-control" id="id_release_artifact" name="release_artifact" value="{{ object.release_artifact|default:'' }}">
    </div>
    <div class="form-group">
      <label for="id_release_number">Release Number</label>
      <input type="text" class="form-control" id="id_release_number" name="release_number" value="{{ object.release_number|default:'' }}">
    </div>
    <div class="form-group">
      <label for="id_release_path">Release Path</label>
      <input type="text" class="form-control" id="id_release_path" name="release_path" value="{{ object.release_path|default:'' }}">
    </div>
    <div class="form-group">
      <label for="id_service_name">Service Name</label>
      <input type="text" class="form-control" id="id_service_name" name="service_name" value="{{ object.service_name|default:'' }}">
    </div>
    <div class="form-group">
      <label for="id_version">Version</label>
      <input type="text" class="form-control" id="id_version" name="version" value="{{ object.version|default:'' }}">
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="id_microui" name="microui" {% if object.microui %}checked {% endif %}>
      <label class="form-check-label" for="id_microui">Micro UI</label>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="id_sql" name="sql" {% if object.sql %} checked {% endif %}>
      <label class="form-check-label" for="id_sql">SQL</label>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="id_uat" name="uat" {% if object.uat %} checked {% endif %}>
      <label class="form-check-label" for="id_uat">UAT</label>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="id_prod" name="prod" {% if object.prod %} checked {% endif %}>
      <label class="form-check-label" for="id_prod">Prod</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

home/templates/home/projectname1.html
{% extends "base/base.html" %}
{% block content %}
<div class="m-5">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Release Artifact</th>
                <th>Release Number</th>
                <th>Release Path</th>
                <th>Service Name</th>
                <th>Version</th>
                <th>MicroUI</th>
                <th>SQL</th>
                <th>UAT</th>
                <th>Prod</th>
            </tr>
        </thead>
        <tbody>
            {% for release in releases %}
            <tr>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.id }} </td>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.date }} </td>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.release_artifact }} </td>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.release_number }} </td>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.release_path }} </td>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.service_name }} </td>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.version }} </td>
                <td style="background-color: {% if release.microui %}green{% else %}orange{% endif %}">{{ release.microui }}</td>
                <td style="background-color: {% if release.sql %}green{% else %}orange{% endif %}">{{ release.sql }} </td>
                <td style="background-color: {% if release.uat %}green{% else %}orange{% endif %}">{{ release.uat }} </td>
                <td style="background-color: {% if release.prod %}green{% else %}orange{% endif %}">{{ release.prod }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

home/templates/home/projectname2.html
{% extends "base/base.html" %}
{% block content %}
Project Name 1
{% endblock content %}

templates/base/base.html
<!doctype html>
<html lang="tr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

</head>

<body>
    {% include "base/snippets/navbar.html" %}
    {% block content %}

    {% endblock content %}
    {% include "base/snippets/footer.html" %}

    {% block script %}

    {% endblock script %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

</body>

</html>

templates/base/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:projectname1' %}">Project 1 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:projectname2' %}">Project 2</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:projectform1' %}">Project 3 </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Project 4 </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>